---
title: "Covid Viz"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load packages
library(tidyverse)
library("ggthemes")
```


```{r}
# load data
case_comp_data <- read.csv("Data/case_comp_data.csv")

death_comp_data <- read.csv("Data/death_comp_data.csv")
```

```{r}
# summary statistics
no_year <- case_comp_data %>% 
  select(-c(year, iso2c)) %>% 
  group_by(name) %>% 
  replace(is.na(.), 0) %>% 
  summarise_all(mean) %>% 
  na_if(0)

min_max <- no_year %>% 
  select(-name) %>% 
  summarise_all(list(min, max))

summary_stats <- no_year %>% 
  select(-name) %>% 
  drop_na() %>% 
  summarise_all(list(mean = mean,max = max,min = min))
```

```{r}
no_year_death <- death_comp_data %>% 
  select(-c(year, iso2c)) %>% 
  group_by(name) %>% 
  replace(is.na(.), 0) %>% 
  summarise_all(mean) %>% 
  na_if(0)

```


```{r}
case_comp_data %>% 
  select(PM2.5.air.pollution..population.exposed.to.levels.exceeding.WHO.guideline.value....of.total.)
```


```{r}
case_comp_data %>%
  select(-iso2c) %>% 
  replace(is.na(.), 0) %>% 
  summarise_at(c("covid_case_pct_pop",
                 "PM2.5.air.pollution..population.exposed.to.levels.exceeding.WHO.guideline.value....of.total."
                  ), sum) %>% 
  pivot_longer(cols = c("covid_case_pct_pop",
                        "PM2.5.air.pollution..population.exposed.to.levels.exceeding.WHO.guideline.value....of.total."
                        )) %>% 
  ggplot(aes(name, value)) +
  geom_col() +
  facet_wrap(~name,scales="free")
```

```{r}
# lay things out spatially
world <- 
  map_data("world") %>% 
  select(long,lat,group,country=region) %>% 
  # standardize the country names
  mutate(country = 
           countrycode::countrycode(country,"country.name","country.name"))

# subset the relevant African countries in the data.
world_comp <- 
  no_year %>% 
  group_by(name) %>% 
  mutate(country = 
           countrycode::countrycode(name,"country.name","country.name")) %>% 
  inner_join(world,by="country")
```


```{r}
no_year %>% 
  filter(name == c("Belgium", "Bhutan")) %>% 
  select(name, covid_case_pct_pop, Poverty.headcount.ratio.at..1.90.a.day..2011.PPP.....of.population.) %>% 
  # mutate(covid_case_pct_pop = covid_case_pct_pop*100) %>% 
  pivot_longer(cols = c("covid_case_pct_pop", "Poverty.headcount.ratio.at..1.90.a.day..2011.PPP.....of.population."), names_to = "variables") %>% 
  ggplot() + 
  geom_bar(aes(x = variables, y = value, fill = name), 
           stat = "identity", position = "dodge")  
```

```{r}
no_year %>% 
  filter(name == c("Belgium", "Bhutan")) %>% 
  select(name, covid_case_pct_pop, Poverty.headcount.ratio.at..1.90.a.day..2011.PPP.....of.population.) %>% 
  # mutate(covid_case_pct_pop = covid_case_pct_pop*100) %>% 
  pivot_longer(cols = c("covid_case_pct_pop", "Poverty.headcount.ratio.at..1.90.a.day..2011.PPP.....of.population."), names_to = "variables") %>% 
  ggplot(aes(value)) +
  geom_density(aes(fill=name), alpha=0.8) 
  
```



```{r}
world_comp %>% 
  slice(-(1:1234)) %>% 
  ggplot(aes(x=long,y=lat,group=group,fill=total_covid_cases)) +
  geom_polygon(color="white",size=.25) +
  scale_fill_gradient2_tableau() +
  theme_map() +
  labs(fill="total covid cases",
       title = "Total Covid Cases"
       ) +
  theme(text=element_text(family = "serif",face="bold",size=14))
```

```{r}
world_comp %>% 
  slice(-(1:1234)) %>% 
  ggplot(aes(x=long,y=lat,group=group,fill=Prevalence.of.underweight..weight.for.age....of.children.under.5.)) +
  geom_polygon(color="white",size=.25) +
  scale_fill_gradient2_tableau() +
  theme_map() +
  theme(text=element_text(family = "serif",face="bold",size=14))
```


```{r}
no_year %>% 
  ggplot(aes(covid_case_pct_pop, Prevalence.of.underweight..weight.for.age....of.children.under.5.)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1) +
  xlim(0,15) +
  ylim(0,15)
```



```{r}
no_year %>% 
  ggplot(aes(covid_case_pct_pop, Prevalence.of.stunting..height.for.age....of.children.under.5.)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1) +
  xlim(0,20) +
  ylim(0,20)
```


```{r}
no_year %>% 
  ggplot(aes(covid_case_pct_pop, PM2.5.air.pollution..population.exposed.to.levels.exceeding.WHO.guideline.value....of.total.)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  xlim(0,50)
```

```{r}
no_year %>% 
  ggplot(aes(covid_case_pct_pop, Adolescents.out.of.school....of.lower.secondary.school.age.)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  xlim(0,25)
```


```{r}
no_year %>% 
  ggplot(aes(covid_case_pct_pop, Children.out.of.school....of.primary.school.age.)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  xlim(0,20)
```


```{r}
no_year %>% 
  ggplot(aes(covid_case_pct_pop, People.using.safely.managed.drinking.water.services....of.population...compare.to.opposite.)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  xlim(0,34)
```


```{r}
no_year %>% 
  ggplot(aes(covid_case_pct_pop, People.with.basic.handwashing.facilities.including.soap.and.water....of.population.)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  xlim(0,40)
```

```{r}
no_year %>% 
  ggplot(aes(covid_case_pct_pop, Low.birthweight.babies....of.births.)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  xlim(0,8)
```

```{r}
no_year_death %>% 
  ggplot(aes(covid_death_per_100000, Maternal.mortality.ratio..modeled.estimate..per.100.000.live.births.)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  xlim(0,400)
```

```{r}
no_year_death %>% 
  ggplot(aes(covid_death_per_1000, mortality.rate..under.5...per.1.000.live.births.)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  ylim(0,400) +
  xlim(0,400)
```

```{r}
no_year_death %>% 
  ggplot(aes(covid_death_per_100000, Mortality.rate.attributed.to.household.and.ambient.air.pollution..age.standardized..per.100.000.population.)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) 
```

```{r}
# this has some extreme outliers if you remove the xlim
no_year_death %>% 
  ggplot(aes(covid_death_per_100000, Mortality.rate.attributed.to.unintentional.poisoning..per.100.000.population.)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  xlim(0,5)
```

```{r}
# also has outliers
no_year_death %>% 
  ggplot(aes(covid_death_per_100000, Mortality.rate.attributed.to.unsafe.water..unsafe.sanitation.and.lack.of.hygiene..per.100.000.population.)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  xlim(0,200)
```


```{r}
# also has outliers
no_year_death %>% 
  ggplot(aes(covid_death_pct_pop, Cause.of.death..by.injury....of.total.)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  xlim(0,7)
```


```{r}
no_year_death %>% 
  ggplot(aes(total_covid_deaths, Refugee.population.by.country.or.territory.of.asylum)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  xlim(0, 7500000)
```


```{r}
no_year_death %>% 
  ggplot(aes(total_covid_deaths, Refugee.population.by.country.or.territory.of.origin)) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  xlim(0, 7500000)
```


